// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import './firebase_options.dart';
// // ...
//   await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2FAtiW3ffJF9BED7TXhSRbPzx_GjP4B4',
    appId: '1:489458845074:web:00c458607c20aceb0bed4b',
    messagingSenderId: '489458845074',
    projectId: 'group-project-2-16d40',
    authDomain: 'group-project-2-16d40.firebaseapp.com',
    storageBucket: 'group-project-2-16d40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB4U5-gY2VMqfX6Vmq_Xbhw0H5YaZkKj4',
    appId: '1:489458845074:android:0fb94f1882ae85e70bed4b',
    messagingSenderId: '489458845074',
    projectId: 'group-project-2-16d40',
    storageBucket: 'group-project-2-16d40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwxZtOAusSHUq2iQkTWJ9rU1s8JdyWpD4',
    appId: '1:489458845074:ios:e6ad0215f8c7f8530bed4b',
    messagingSenderId: '489458845074',
    projectId: 'group-project-2-16d40',
    storageBucket: 'group-project-2-16d40.appspot.com',
    iosClientId:
        '489458845074-4k63uqdf3796g3ck8ietq84o92t9pn8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwxZtOAusSHUq2iQkTWJ9rU1s8JdyWpD4',
    appId: '1:489458845074:ios:e6ad0215f8c7f8530bed4b',
    messagingSenderId: '489458845074',
    projectId: 'group-project-2-16d40',
    storageBucket: 'group-project-2-16d40.appspot.com',
    iosClientId:
        '489458845074-4k63uqdf3796g3ck8ietq84o92t9pn8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
